### ISSUE TITLE
Regarding xunet accuracy

### ISSUE THREAD

**Issue by brijeshiitg** [Sourish1997/steganalysis#1]
Does Xu net model give accuracy as suggested by authors?

**Comment by Sourish1997** [comment]
I think you might be referring to a different paper. The paper I have referred to can be found in the 'reference papers' folder. Since I have used a different dataset, the results should not be directly compared. However, if you still want to compare, my CF model performs slightly better than that reported in the paper, even when working on images generated with a slightly higher hiding ratio. Hope this helps.
